function [layers, options] = setup_rnn(numChannels, XTest, TTest)
    layers = [
        sequenceInputLayer(numChannels)
        lstmLayer(128, 'OutputMode', 'sequence')
        fullyConnectedLayer(6)
        regressionLayer];

    options = trainingOptions("adam", ...
        MaxEpochs=100, ...
        SequencePaddingDirection="left", ...
        Shuffle="every-epoch", ...
        Plots="training-progress", ...
        Verbose=0, ...
        ValidationData={XTest, TTest}, ...
        ValidationFrequency = 25);
end