load('data/full-data-matlab/FullData_NoVehXYZ_noB_noWaypoints_081522.mat')  

numChannels = size(XTrain{1}, 1)
numRecChannels = size(TTrain{1}, 1)
[layers, options] = setup_full_residual_gru(numChannels, numRecChannels, XTest, TTest);

%     MaxEpochs=5, ...
init_options = trainingOptions("adam", ...
    MiniBatchSize=20, ...
    SequencePaddingDirection="right", ...
    Plots="training-progress", ...
    Shuffle='never', ...
    ValidationData={XTest, TTest}, ...
    ValidationFrequency = 100, ...
    ValidationPatience = 2);
[net, info] = trainNetwork(XTrain,TTrain,layers,init_options);
%     
outputFile = fullfile("data/networks/full-nets", 'SingleStepNet_NoVehXYZ_noB_noWaypoints_1024units.mat');
save(outputFile, 'net', 'info');